name: A workflow that check if links in README.md is working
on: push
jobs:
  build:
    name: Check if README.md links works
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fdagreat/linksnitch@main
        with:
          allowedStatusCodes: '[200 , 201 , 405]'